version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: viraj5132
          password: $Docker_PWD # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          docker build -t CircleCI-Public/circleci-demo-docker:latest .
          echo $Docker_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push CircleCI-Public/circleci-demo-docker:latest
# version: 2.1

# workflows:
#   test-deploy:
#     jobs:
#       - build:
#       - aws-ecr/build_and_push_image:
#           region: us-east-1
#           account-url: ${AWS_ECR_ACCOUNT_URL}
#           repo: ${CIRCLE_PROJECT_REPONAME}
#           tag: ${CIRCLE_BUILD_NUM}
            
#   jobs:
#     docker_hub_build_push_image:
#       machine:
#         - image: ubuntu-2204:2022.04.2
#       steps:
#         - checkout
#         - run: 
#             name: Build and push Docker image to ECR
#             command: |
#                docker build -t ${DOCKER_LOGIN}/node-app:${TAG} .
#                docker login -u ${DOCKER_LOGIN} -p ${Docker_PWD}
#                docker push ${DOCKER_LOGIN}/node-app       
