version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: viraj5132
          password: $Docker_PWD # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          docker build -t $DOCKER_LOGIN/circleci-node:latest .
          echo $Docker_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push $DOCKER_LOGIN/circleci-node:latest
